services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - buyme-network
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: buyme
      POSTGRES_PASSWORD: buyme
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - buyme-network
    volumes:
      - "./data/redis:/data"
  server:
    build: ./server
    tty: true
    volumes:
      - .:/go/src/buyme
    ports:
      - "2222:2222"
    depends_on:
      - db
    networks:
      - buyme-network
    command:
      /bin/bash -c "sleep 10 && go run server.go"
  # web:
  #   build: ./web
  #   tty: true
  #   volumes:
  #     - ./web:/buyme/web
  #   ports:
  #     - "5352:5352"
networks:
  buyme-network:
    external: true