services:
  db:
    image: postgres
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: buyme
  server:
    build: ./server
    tty: true
    volumes:
      - .:/go/src/buyme
    ports:
      - "2222:2222"
    depends_on:
      - db
    networks:
      - buyme-network
  # web:
  #   build: ./web
  #   tty: true
  #   volumes:
  #     - ./web:/buyme/web
  #   ports:
  #     - "5352:5352"
networks:
  buyme-network:
    external: true