services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - buyme-network
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: buyme
      POSTGRES_PASSWORD: buyme
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - buyme-network
    volumes:
      - "./data/redis:/data"
  server:
    build: ./server
    tty: true
    volumes:
      - .:/go/src/buyme
    ports:
      - "2222:2222"
    depends_on:
      - db
    networks:
      - buyme-network
    command:
      /bin/bash -c "sleep 10 && go run server.go"
  front:
    build: ./front
    tty: true
    networks:
      - buyme-network
    volumes:
      - ./front:/buyme/front
    ports:
      - "3000:3000"
networks:
  buyme-network:
    external: true